### ISSUE TITLE
CRT Shader Filter on the canvas?

### ISSUE THREAD

**Issue by shiffman** [Lumon-Industries/Macrodata-Refinement#19]

**Comment by kfahn22** [comment]
Your steams are so fun to watch!  I just ported a pixel art emulation from Shadertoy.  (It uses an image I uploaded as a texture.)

https://editor.p5js.org/kfahn/sketches/jQ91BX22J

**Comment by kfahn22** [comment]
I realized I don't actually know what you want to do with the CRT shader filter.  The first makes the  image more pixelated.  This one is  a CRT shader if your goal is to make the canvas look like an old time TV screen.  Both provided as a reference, which you probably don't even need.

https://editor.p5js.org/kfahn/sketches/HG9Ugdkki

**Comment by jhrtn** [comment]
https://user-images.githubusercontent.com/17256474/162527996-33577595-4823-49ba-aab1-2617b23ae69e.mov

I've been having a (shader) pass at this as well, following quite a[ simple example from babylon.js ](https://babylonjs.medium.com/retro-crt-shader-a-post-processing-effect-study-1cb3f783afbc)

It's quite effective, a good way to add the blue tint too.

Issues:
- it's very slow! (I'm guessing like 5-10FPS right now) I'm taking a copy of the canvas context at the end of the draw loop, passing that into the shader as a sampler2D texture and then drawing that output to the screen. Maybe this would be improved by using an offscreen canvas?
- Everything seems to be 4x zoomed in, I could only take the above screen recording by zooming out my Chrome window to 50% (that's why the bins at the bottom look so small)
- When a modal image is drawn to the screen it shoots up to the top left, I think a push()/pop() must be messing things up somewhere, the MDE moment is fine though

https://user-images.githubusercontent.com/17256474/162528991-b920fe73-d06f-45ec-a907-8c5ff5a2f625.mov

<img width="604" alt="Screenshot 2022-04-08 at 21 59 20" src="https://user-images.githubusercontent.com/17256474/162529199-e60e2879-0e81-4dbc-bae5-26f9a83ec97b.png">


I'll tidy things up and share through a PR

**Comment by kfahn22** [comment]
Your code seems much simpler--could you share it?  I am not sure how to copy the canvas and input that into the shader.

**Comment by shiffman** [comment]
I am going to close this but open a new issue for optimizing shader for mobile?
